routes/web.php
<?php

Route::get('/', function () {
    return redirect()->route('login');
});

//Rutas de Login
Auth::routes();

//Rutas de Dashboard
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/dashboard/list-desktops', 'DashboardController@desktop')->name('dashboard.list-desktops');
Route::get('/dashboard/list-laptops', 'DashboardController@laptop')->name('dashboard.list-laptops');
Route::get('/dashboard/list-servers', 'DashboardController@server')->name('dashboard.list-servers');
Route::get('/dashboard/list-peripherals', 'DashboardController@peripheral')->name('dashboard.list-peripherals');
Route::get('/dashboard/list-printers', 'DashboardController@printer')->name('dashboard.list-printers');
Route::get('/dashboard/list-networks', 'DashboardController@network')->name('dashboard.list-networks');

//Rutas de empleados
Route::post('/employees/ajax', 'EmployeeController@ajax');
Route::resource('/employees', 'EmployeeController');

//Rutas de departamentos
Route::resource('/departments', 'DepartmentController');
Route::resource('/positions', 'PositionController');
Route::resource('/articles', 'ArticleController');
Route::resource('/categories', 'CategoryController');
Route::resource('/brands', 'BrandController');

//Rutas de Activos Fijos
Route::get('/fixed-assets/assign-fixed-asset', 'FixedassetController@showFormAssignFixedAsset')->name('fixed-assets.assign-fixed-asset');
Route::post('/fixed-assets/assign-fixed-asset', 'FixedassetController@assignFixedAsset')->name('fixed-assets.assign-fixed-asset');
Route::get('/fixed-assets/assign-fixed-asset/{fixed_asset}/edit', 'FixedassetController@showFormEditAssignFixedAsset')->name('fixed-assets.edit-assign-fixed-asset');
Route::put('/fixed-assets/assign-fixed-asset/{fixed_asset}', 'FixedassetController@updateAssignFixedAsset')->name('fixed-assets.update-assign-fixed-asset');

Route::resource('/fixed-assets', 'FixedassetController');
Route::resource('/maintenances', 'MaintenanceController');
Route::resource('/storage-cellars', 'StoragecellarController');
Route::post('/delivery-certificates/ajax/edit', 'DeliverycertificateController@ajaxEdit');
Route::post('/delivery-certificates/ajax/delete', 'DeliverycertificateController@ajaxDelete');
Route::resource('/delivery-certificates', 'DeliverycertificateController');
Route::resource('/users', 'UserController');
Route::resource('/roles', 'RoleController');
Route::resource('/status', 'StatusController');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\{Article, Category};

class DashboardController extends Controller
{

  public function __construct()
  {
    $this->middleware('auth');
  }

  public function index()
  {
    $categories = Category::categories('name')->get();
    return view('dashboard', compact(['categories']));
  }

  public function desktop()
  {
    $count = 1;
    $desktops = Article::where('category_id',  6)->orderBy('name')->paginate(10);
    $countAricles = $desktops->count();

    return view('modules.dashboard.desktops.list-desktop', compact(['desktops', 'count']));
  }

  public function laptop()
  {
    $count = 1;
    $laptops = Article::where('category_id', 1)->orderBy('name')->paginate(10);
    return view('modules.dashboard.laptops.list-laptop', compact(['laptops', 'count']));
  }

  public function server()
  {
    $count = 1;
    $servers = Article::where('category_id', 1)->orderBy('name')->paginate(10);
    return view('modules.dashboard.servers.list-server', compact(['servers', 'count']));
  }

  public function peripheral()
  {
    $count = 1;
    $peripherals = Article::where('category_id', 4)->orderBy('name')->paginate(10);
    return view('modules.dashboard.peripherals.list-peripheral', compact(['peripherals', 'count']));
  }

  public function printer()
  {
    $count = 1;
    $printers = Article::where('category_id',  2)->orderBy('name')->paginate(10);
    return view('modules.dashboard.printers.list-printer', compact(['printers', 'count']));
  }

  public function network()
  {
    $count = 1;
    $networks = Article::where('category_id',  3)->orderBy('name')->paginate(10);
    return view('modules.dashboard.networks.list-network', compact(['networks', 'count']));
  }
}

resources/views/modules/dashboard/networks/list-network.blade.php
@extends('template.layout')
@section('main-content')
{{--overview start--}}
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header"><i class="fa fa-desktop"></i>Networks </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home"></i><a href="{{ route('dashboard') }}">Dashboard</a></li>
        <li><i class="fa fa-home"></i><a href="{{ route('articles.index') }}">Articles</a></li>
        <li><i class="fa fa-desktop"></i>Networks</li>
      </ol>
    </div>
  </div>
</section>
{{--overview end--}}
{{--main content start--}}
<div class="row">
  <div class="col-lg-12">
    <div class="panel-body panel-body-j">
      <div class="row">
        <div class="col-lg-12">
          <section class="panel">
            <div class="table-responsive">
              <table class="table table-striped table-advance table-hover">
                <caption class="page-header-table">Networks</caption>
                <tbody class="form-horizontal">
                  <tr class="form-group row">
                    <th class="col-lg-1 col-sm-1 center"> N°</th>
                    <th class="col-lg-2 col-sm-2 center"><i class="fa fa-desktop"></i> Name</th>
                    <th class="col-lg-2 col-sm-2 center"><i class="fa fa-linode"></i> Brad</th>
                    <th class="col-lg-2 col-sm-2 center"><i class="fa fa-modx"></i> Model</th>
                    <th class="col-lg-2 col-sm-2 center"><i class="fa fa-archive"></i> Quantity</th>
                    <th class="col-lg-3 col-sm-2"><i class="icon_cogs"></i> Action</th>
                  </tr>
                  @foreach ($networks as $network)
                  @if (!$network->deleted_at)
                  <tr class="form-group">
                    <td class="col-lg-1 col-sm-1 center">{{ $count }}</td>
                    <td class="col-lg-2 col-sm-2 center">{{ $network->name }}</td>
                    <td class="col-lg-2 col-sm-2 center">{{ $network->brand }}</td>
                    <td class="col-lg-2 col-sm-2 center">{{$network->model}}</td>
                    <td class="col-lg-2 col-sm-2 center">515</td>
                    <td class="col-sm-3">
                      <div class="btn-group">
                        <a class="btn btn-primary" href="{{ route('articles.edit', $network->id) }}"><i
                            class="icon_plus_alt2"></i></a>
                        <a class="btn btn-success" href="{{ route('articles.show', $network->id) }}"><i
                            class="icon_check_alt2"></i></a>
                        <form class="form-delete" method="POST" action="{{ route('articles.destroy', $network->id) }}">
                          <button class="btn btn-danger form-delete-button" type="submit"><i
                              class="icon_close_alt2"></i></button>
                          {{ csrf_field() }}
                          {{ method_field('DELETE') }}
                        </form>
                      </div>
                    </td>
                  </tr>
                  @php $count++ @endphp
                  @endif
                  @endforeach
                </tbody>
              </table>
              {{-- paginación --}}
              <div class="row">
                <div class="col-lg-offset-5">
                  {{$networks->links() }}
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>
{{--main content end--}}
@endsection