routes/web.php
<?php

Route::get('/', function () {
    return redirect()->route('login');
});

//Rutas de Login
Auth::routes();

//Rutas de Dashboard
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/dashboard/list-desktops', 'DashboardController@desktop')->name('dashboard.list-desktops');
Route::get('/dashboard/list-laptops', 'DashboardController@laptop')->name('dashboard.list-laptops');
Route::get('/dashboard/list-servers', 'DashboardController@server')->name('dashboard.list-servers');
Route::get('/dashboard/list-peripherals', 'DashboardController@peripheral')->name('dashboard.list-peripherals');
Route::get('/dashboard/list-printers', 'DashboardController@printer')->name('dashboard.list-printers');
Route::get('/dashboard/list-networks', 'DashboardController@network')->name('dashboard.list-networks');

//Rutas de empleados
Route::post('/employees/ajax', 'EmployeeController@ajax');
Route::resource('/employees', 'EmployeeController');

//Rutas de departamentos
Route::resource('/departments', 'DepartmentController');
Route::resource('/positions', 'PositionController');
Route::resource('/articles', 'ArticleController');
Route::resource('/categories', 'CategoryController');
Route::resource('/brands', 'BrandController');

//Rutas de Activos Fijos
Route::get('/fixed-assets/assign-fixed-asset', 'FixedassetController@showFormAssignFixedAsset')->name('fixed-assets.assign-fixed-asset');
Route::post('/fixed-assets/assign-fixed-asset', 'FixedassetController@assignFixedAsset')->name('fixed-assets.assign-fixed-asset');
Route::get('/fixed-assets/assign-fixed-asset/{fixed_asset}/edit', 'FixedassetController@showFormEditAssignFixedAsset')->name('fixed-assets.edit-assign-fixed-asset');
Route::put('/fixed-assets/assign-fixed-asset/{fixed_asset}', 'FixedassetController@updateAssignFixedAsset')->name('fixed-assets.update-assign-fixed-asset');

Route::resource('/fixed-assets', 'FixedassetController');
Route::resource('/maintenances', 'MaintenanceController');
Route::resource('/storage-cellars', 'StoragecellarController');
Route::post('/delivery-certificates/ajax/edit', 'DeliverycertificateController@ajaxEdit');
Route::post('/delivery-certificates/ajax/delete', 'DeliverycertificateController@ajaxDelete');
Route::resource('/delivery-certificates', 'DeliverycertificateController');
Route::resource('/users', 'UserController');
Route::resource('/roles', 'RoleController');
Route::resource('/status', 'StatusController');

resources/views/template/blocks/aside.blade.php
<aside>
  <div id="sidebar" class="nav-collapse">
    {{-- sidebar menu start--}}
    <ul class="sidebar-menu">
      <li class="active">
        <a class="" href="{{ route('dashboard') }}">
          <i class="fa fa-tachometer"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="fa fa-users" aria-hidden="true"></i>
          <span>Employees</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('employees.create') }}">Create Employee</a></li>
          <li><a class="" href="{{ route('employees.index') }}">List Employees</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="fa fa-sitemap" aria-hidden="true"></i>
          <span>Departments</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('departments.create') }}">Create Department</a></li>
          <li><a class="" href="{{ route('departments.index') }}">List Departments</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="fa fa-handshake-o" aria-hidden="true"></i>
          <span>Positions</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('positions.create') }}">Create Position</a></li>
          <li><a class="" href="{{ route('positions.index') }}">Positions List</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="fa fa-desktop" aria-hidden="true"></i>
          <span>Articles</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('articles.create') }}">Crear Article</a></li>
          <li><a class="" href="{{ route('articles.index') }}">List Articles</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="fa fa-tachometer" aria-hidden="true"></i>
          <span>Categories</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('categories.create') }}">Create Category</a></li>
          <li><a class="" href="{{ route('categories.index') }}">List Categories</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="fa fa-linode" aria-hidden="true"></i>
          <span>Brands</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('brands.create') }}">Create Brand</a></li>
          <li><a class="" href="{{ route('brands.index') }}">List Brands</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="icon_genius"></i>
          <span>Fixed Assets</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('fixed-assets.create') }}">Create Fixed Asset</a></li>
          <li><a class="" href="{{ route('fixed-assets.assign-fixed-asset') }}">Assign Fixed Asset</a></li>
          <li><a class="" href="{{ route('fixed-assets.index') }}">List Fixed Assets</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="" title="Delivery Certificate">
          <i class="icon_documents_alt"></i>
          <span>Delivery Certif</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('delivery-certificates.create') }}" title="Create Delivery Certificate">Create
              Delivery Certif</a></li>
          <li><a class="" href="{{ route('delivery-certificates.index') }}">List Orders</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="icon_tools"></i>
          <span>Maintenances</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('maintenances.create') }}">Create Maintenance</a></li>
          <li><a class="" href="{{ route('maintenances.index') }}">Listar Ordernes</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="" title="Delivery Certificate">
          <i class="fa fa-archive" aria-hidden="true"></i>
          <span>Storage Cellar</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('storage-cellars.create') }}" title="Create Delivery Certificate">Create
              Delivery Certif</a></li>
          <li><a class="" href="{{ route('storage-cellars.index') }}">List Orders</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="icon_group"></i>
          <span>Users</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('users.create') }}">Create User</a></li>
          <li><a class="" href="{{ route('users.index') }}">List Users</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="fa fa-address-book-o" aria-hidden="true"></i>
          <span>Roles</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('roles.create') }}">Create Relo</a></li>
          <li><a class="" href="{{ route('roles.index') }}">List Relos</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="fa fa-list-alt" aria-hidden="true"></i>
          <span>Status</span>
          <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{{ route('status.create') }}">Create Status</a></li>
          <li><a class="" href="{{ route('status.index') }}">List Status</a></li>
        </ul>
      </li>
    </ul>
    {{-- sidebar menu end--}}
  </div>
</aside>

resources/views/template/blocks/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link href="{{asset('/favicon.ico')}}" rel="shortcut icon">
    <!-- Bootstrap CSS -->    
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{{asset('css/bootstrap-theme.css')}}" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="{{asset('css/elegant-icons-style.css')}}" rel="stylesheet" />
    <link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet" />    
    <!-- full calendar css-->
    <link href="{{asset('assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css')}}" rel="stylesheet" />
	<link href="{{asset('assets/fullcalendar/fullcalendar/fullcalendar.css')}}" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href="{{asset('assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css')}}" rel="stylesheet" type="text/css" media="screen"/>
    <!-- owl carousel -->
    <link href="{{asset('css/owl.carousel.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('css/jquery-jvectormap-1.2.2.css')}}" rel="stylesheet">
    <!-- Custom styles -->
	<link href="{{asset('css/fullcalendar.css')}}" rel="stylesheet">
	<link href="{{asset('css/widgets.css')}}" rel="stylesheet">
    <link href="{{asset('css/style-responsive.css')}}" rel="stylesheet" />
	<link href="{{asset('css/xcharts.min.css')}}" rel=" stylesheet">	
	<link href="{{asset('css/jquery-ui-1.10.4.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/style.css')}}" rel="stylesheet">
    <link href="{{asset('css/myStyle.css')}}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
      <script src="{{asset('js/html5shiv.js')}}"></script>
      <script src="{{asset('js/respond.min.js')}}"></script>
      <script src="{{asset('js/lte-ie7.js')}}"></script>
    <![endif]-->
  </head>

resources/views/template/blocks/header.blade.php
<header class="header dark-bg">
  <div class="toggle-nav">
    <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom">
      <i class="icon_menu"></i>
    </div>
  </div>
  {{--logo start--}}
  <a href="{{route('dashboard')}}" class="logo">Mult<span class="lite">Inventory</span></a> {{--logo end--}}
  <div class="nav search-row" id="top_menu">
    {{-- search form start --}}
    {{-- <ul class="nav top-menu">
      <li>
        <form class="navbar-form">
          <input class="form-control" placeholder="Search" type="text">
        </form>
      </li>
    </ul> --}}
    {{-- search form end --}}
  </div>
  <div class="top-nav notification-row">
    {{-- notificatoin dropdown start--}}
    <ul class="nav pull-right top-menu">
      <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
          <span class="profile-ava">
            <img alt="" src="{{asset('img/avatar-mini2.jpg')}}">
          </span>
        <span class="username">{{ Auth::user()->user_name}}</span>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu extended logout">
          <li class="log-arrow-up"></li>
          <li class="eborder-top">
          <a href="{{route('users.show', Auth::user()->id)}}"><i class="icon_profile"></i> My Profile</a>
          </li>
          <li>
            <a href="{{route('logout')}}" onclick="event.preventDefault();
            document.getElementById('logout-form').submit();"><i class="icon_key_alt"></i> Log Out</a>
            <form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
          </li>
        </ul>
      </li>
      {{-- user login dropdown end --}}
    </ul>
    {{-- notificatoin dropdown end--}}
  </div>
</header>

resources/views/template/blocks/scripts.blade.php
<script src="{{asset('js/jquery.js')}}"></script>
<script src="{{asset('js/jquery-ui-1.10.4.min.js')}}"></script>
<script src="{{asset('js/jquery-1.8.3.min.js')}}"></script>
<script src="{{asset('js/jquery-ui-1.9.2.custom.min.js')}}"></script>
{{-- bootstrap --}}
<script src="{{asset('js/bootstrap.min.js')}}"></script>
{{-- nice scroll --}}
<script src="{{asset('js/jquery.scrollTo.min.js')}}"></script>
<script src="{{asset('js/jquery.nicescroll.js')}}"></script>
{{-- charts scripts --}}
<script src="{{asset('assets/jquery-knob/js/jquery.knob.js')}}"></script>
<script src="{{asset('js/jquery.sparkline.js')}}"></script>
<script src="{{asset('assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js')}}"></script>
<script src="{{asset('js/owl.carousel.js')}}"></script>
{{-- jQuery full calendar --}}
<script src="{{asset('js/fullcalendar.min.js')}}"></script> 
{{-- Full Google Calendar - Calendar --}}
<script src="{{asset('assets/fullcalendar/fullcalendar/fullcalendar.js')}}"></script>
{{--script for this page only--}}
<script src="{{asset('js/calendar-custom.js')}}"></script>
<script src="{{asset('js/jquery.rateit.min.js')}}"></script>
{{-- custom select --}}
<script src="{{asset('js/jquery.customSelect.min.js')}}"></script>
<script src="{{asset('assets/chart-master/Chart.js')}}"></script>

{{--custome script for all page--}}
<script src="{{asset('js/scripts.js')}}"></script>
{{-- custom script for this page--}}
<script src="{{asset('js/sparkline-chart.js')}}"></script>
<script src="{{asset('js/easy-pie-chart.js')}}"></script>
<script src="{{asset('js/jquery-jvectormap-1.2.2.min.js')}}"></script>
<script src="{{asset('js/jquery-jvectormap-world-mill-en.js')}}"></script>
<script src="{{asset('js/xcharts.min.js')}}"></script>
<script src="{{asset('js/jquery.autosize.min.js')}}"></script>
<script src="{{asset('js/jquery.placeholder.min.js')}}"></script>
<script src="{{asset('js/gdp-data.js')}}"></script>	
<script src="{{asset('js/morris.min.js')}}"></script>
<script src="{{asset('js/sparklines.js')}}"></script>	
<script src="{{asset('js/charts.js')}}"></script>
<script src="{{asset('js/jquery.slimscroll.min.js')}}"></script>
{{-- <script src="{{asset('js/myscript.js')}}"></script> --}}
<script>
      //knob
      $(function() {
        $(".knob").knob({
          'draw' : function () { 
            $(this.i).val(this.cv + '%')
          }
        })
      });

      //carousel
      $(document).ready(function() {
        $("#owl-slider").owlCarousel({
          navigation : true,
          slideSpeed : 300,
          paginationSpeed : 400,
          singleItem : true

        });
      });

      //custom select box

      $(function(){
        $('select.styled').customSelect();
      });

      /* ---------- Map ---------- */
      $(function(){
       $('#map').vectorMap({
         map: 'world_mill_en',
         series: {
           regions: [{
             values: gdpData,
             scale: ['#000', '#000'],
             normalizeFunction: 'polynomial'
           }]
         },
         backgroundColor: '#eef3f7',
         onLabelShow: function(e, el, code){
           el.html(el.html()+' (GDP - '+gdpData[code]+')');
         }
       });
     });
   </script>