routes/web.php
<?php

Route::get('/', function () {
    return redirect()->route('login');
});

//Rutas de Login
Auth::routes();

//Rutas de Dashboard
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/dashboard/list-desktops', 'DashboardController@desktop')->name('dashboard.list-desktops');
Route::get('/dashboard/list-laptops', 'DashboardController@laptop')->name('dashboard.list-laptops');
Route::get('/dashboard/list-servers', 'DashboardController@server')->name('dashboard.list-servers');
Route::get('/dashboard/list-peripherals', 'DashboardController@peripheral')->name('dashboard.list-peripherals');
Route::get('/dashboard/list-printers', 'DashboardController@printer')->name('dashboard.list-printers');
Route::get('/dashboard/list-networks', 'DashboardController@network')->name('dashboard.list-networks');

//Rutas de empleados
Route::post('/employees/ajax', 'EmployeeController@ajax');
Route::resource('/employees', 'EmployeeController');

//Rutas de departamentos
Route::resource('/departments', 'DepartmentController');
Route::resource('/positions', 'PositionController');
Route::resource('/articles', 'ArticleController');
Route::resource('/categories', 'CategoryController');
Route::resource('/brands', 'BrandController');

//Rutas de Activos Fijos
Route::get('/fixed-assets/assign-fixed-asset', 'FixedassetController@showFormAssignFixedAsset')->name('fixed-assets.assign-fixed-asset');
Route::post('/fixed-assets/assign-fixed-asset', 'FixedassetController@assignFixedAsset')->name('fixed-assets.assign-fixed-asset');
Route::get('/fixed-assets/assign-fixed-asset/{fixed_asset}/edit', 'FixedassetController@showFormEditAssignFixedAsset')->name('fixed-assets.edit-assign-fixed-asset');
Route::put('/fixed-assets/assign-fixed-asset/{fixed_asset}', 'FixedassetController@updateAssignFixedAsset')->name('fixed-assets.update-assign-fixed-asset');

Route::resource('/fixed-assets', 'FixedassetController');
Route::resource('/maintenances', 'MaintenanceController');
Route::resource('/storage-cellars', 'StoragecellarController');
Route::post('/delivery-certificates/ajax/edit', 'DeliverycertificateController@ajaxEdit');
Route::post('/delivery-certificates/ajax/delete', 'DeliverycertificateController@ajaxDelete');
Route::resource('/delivery-certificates', 'DeliverycertificateController');
Route::resource('/users', 'UserController');
Route::resource('/roles', 'RoleController');
Route::resource('/status', 'StatusController');

app/StorageCellar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class StorageCellar extends Model
{

    use SoftDeletes;

    protected $dates = ['deleted_at'];
    
    protected $table = 'storage_cellars';

    protected $fillable = ['name', 'description','status'];

    public function fixedAssets()
    {
       return $this->hasMany(FixedAsset::class);
    }
}

app/Http/Controllers/StoragecellarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\StorageCellar;
use App\Http\Requests\StorageCellarRequest;

class StoragecellarController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $storage_cellars = StorageCellar::all();
        $count = 1;
        return view('modules.storage_cellar.list-storage-cellar', compact(['storage_cellars', 'count']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('modules.storage_cellar.create-storage-cellar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorageCellarRequest $request)
    {
        StorageCellar::create($request->all());
        return back()->with('status', 'Registro exitoso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $storage_cellar = StorageCellar::findOrFail($id);
        return view('modules.storage_cellar.edit-storage-cellar', compact('storage_cellar'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StorageCellarRequest $request, $id)
    {
        StorageCellar::findOrFail($id)->update($request->all());
        return back()->with('status', 'Registro Actualizado con éxito!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        StorageCellar::findOrFail($id)->delete();
        return back();
    }
}

resources/views/modules/storage_cellar/create-storage-cellar.blade.php
@extends('template')
@section('main-content')
{{--overview start--}}
<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header"><i class="fa fa-archive"></i>Storage Cellar Module</h3>
    <ol class="breadcrumb">
      <li><i class="fa fa-home"></i><a href="{{ route('dashboard') }}">Dashboard</a></li>
      <li><i class="fa fa-archive"></i><a href="{{ route('storage-cellars.index') }}">Storage Cellar</a></li>
      <li><i class="fa fa-steam"></i>Create Department</li>
    </ol>
  </div>
</div>
{{--overview end--}}
{{--main content start--}}
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <h3>Storage Cellar Registration Form</h3>
      </header>
      <div class="panel-body">
        <div class="form">
          <form class="form-validate form-horizontal " id="register_form" method="POST"
            action="{{ route('storage-cellars.store') }}">
            @if (session()->has('status'))
            <div class="alert alert-success col-lg-offset-2" role="alert">
              {{ session('status') }}
            </div>
            @endif
            <div class="form-group ">
              <label for="name" class="control-label col-lg-2">Name <span class="required">*</span></label>
              <div class="col-lg-10">
                @if ($errors->has('name'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first('name') }}
                </div>
                @endif
                <input class=" form-control" id="name" name="name" type="text" value="{{ old('name')}}" />
              </div>
            </div>
            <div class="form-group ">
              <label for="description" class="control-label col-lg-2">Description <span
                  class="required">*</span></label>
              <div class="col-lg-10">
                @if ($errors->has('description'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first('description') }}
                </div>
                @endif
                <textarea name="description" id="description" class="form-control">{{ old('description') }}</textarea>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="submit">Save</button>
                <a class="btn btn-danger" href="{{ route('storage-cellars.index') }}">Cancel</a>
              </div>
            </div>
            {{ csrf_field() }}
          </form>
        </div>
      </div>
    </section>
  </div>
</div>
{{--main content end--}}
@endsection

resources/views/modules/storage_cellar/edit-storage-cellar.blade.php
@extends('template')
@section('main-content')
{{--overview start--}}
<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header"><i class="fa fa-archive"></i>Storage Cellar Module</h3>
    <ol class="breadcrumb">
      <li><i class="fa fa-home"></i><a href="{{ route('dashboard') }}">Dashboard</a></li>
      <li><i class="fa fa-archive"></i><a href="{{ route('storage-cellars.index') }}">Storage Cellars</a></li>
      <li><i class="fa fa-steam"></i>Update Storage Cellar</li>
    </ol>
  </div>
</div>
{{--overview end--}}
{{--main content start--}}
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <h3>Storage Cellar Update Form</h3>
      </header>
      <div class="panel-body">
        <div class="form">
          <form class="form-validate form-horizontal " id="register_form" method="POST"
            action="{{ route('storage-cellars.update', $storage_cellar->id) }}">
            @if (session()->has('status'))
            <div class="alert alert-success col-lg-offset-2" role="alert">
              {{ session('status') }}
            </div>
            @endif
            <div class="form-group ">
              <label for="name" class="control-label col-lg-2">Name <span class="required">*</span></label>
              <div class="col-lg-10">
                @if ($errors->has('name'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first('name') }}
                </div>
                @endif
                <input class=" form-control" id="name" name="name" type="text"
                  value="{{ old('name') ?? $storage_cellar->name }}" />
              </div>
            </div>
            <div class="form-group ">
              <label for="description" class="control-label col-lg-2">Description <span
                  class="required">*</span></label>
              <div class="col-lg-10">
                @if ($errors->has('description'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first('description') }}
                </div>
                @endif
                <textarea name="description" id="description"
                  class="form-control">{{ old('description') ?? $storage_cellar->description }}</textarea>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="submit">Update</button>
                <a class="btn btn-danger" href="{{ route('storage-cellars.index') }}">Cancel</a>
              </div>
            </div>
            {{ csrf_field() }}
            {{ method_field('PUT') }}
          </form>
        </div>
      </div>
    </section>
  </div>
</div>
{{--main content end--}}
@endsection

resources/views/modules/storage_cellar/list-storage-cellar.blade.php
@extends('template')
@section('main-content')
{{--overview start--}}
<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header"><i class="fa fa-archive"></i>Storage Cellar Module</h3>
    <ol class="breadcrumb">
      <li><i class="fa fa-home"></i><a href="{{ route('dashboard') }}">Dashboard</a></li>
      <li><i class="fa fa-archive"></i>Storage Cellars</li>
    </ol>
  </div>
</div>
{{--overview end--}}
{{--main content start--}}
<div class="row">
  <div class="col-lg-12">
    <div class="panel">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <section class="panel">
              <div class="table-responsive">
                <table class="table table-striped table-advance table-hover">
                  <caption class="page-header-table">Storage Cellars</caption>
                  <tbody class="form-horizontal">
                    <tr class="form-group">
                      <th class="col-lg-1 col-sm-1 center"> N°</th>
                      <th class="col-lg-3 col-sm-2"><i class="fa fa-archive" aria-hidden="trues"></i> Name</th>
                      <th class="col-lg-5 col-sm-6"><i class="fa fa-file-text-o"></i> Description</th>
                      <th class="col-lg-3 col-sm-3"><i class="icon_cogs"></i> Action</th>
                    </tr>
                    @foreach($storage_cellars as $storage_cellar)
                    @if (!$storage_cellar->deleted_at)
                    <tr class="form-group">
                      <td class="col-lg-1 col-sm-1 center">{{ $count }}</td>
                      <td class="col-lg-3 col-sm-2">{{ $storage_cellar->name }}</td>
                      <td class="col-lg-5 col-sm-3 col-sm-3">{{ $storage_cellar->description }}</td>
                      <td class="col-sm-3">
                        <div class="btn-group">
                          <a class="btn btn-primary" href="{{ route('storage-cellars.edit', $storage_cellar->id) }}"><i
                              class="icon_plus_alt2"></i></a>
                          <form class="form-delete" method="POST"
                            action="{{ route('storage-cellars.destroy', $storage_cellar->id) }}">
                            <button class="btn btn-danger form-delete-button" type="submit"><i
                                class="icon_close_alt2"></i></button>
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                          </form>
                        </div>
                      </td>
                    </tr>
                    @php $count++ @endphp
                    @endif
                    @endforeach
                  </tbody>
                </table>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{{--main content end--}}
@endsection