routes/web.php
<?php

Route::get('/', function () {
    return redirect()->route('login');
});

//Rutas de Login
Auth::routes();

//Rutas de Dashboard
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/dashboard/list-desktops', 'DashboardController@desktop')->name('dashboard.list-desktops');
Route::get('/dashboard/list-laptops', 'DashboardController@laptop')->name('dashboard.list-laptops');
Route::get('/dashboard/list-servers', 'DashboardController@server')->name('dashboard.list-servers');
Route::get('/dashboard/list-peripherals', 'DashboardController@peripheral')->name('dashboard.list-peripherals');
Route::get('/dashboard/list-printers', 'DashboardController@printer')->name('dashboard.list-printers');
Route::get('/dashboard/list-networks', 'DashboardController@network')->name('dashboard.list-networks');

//Rutas de empleados
Route::post('/employees/ajax', 'EmployeeController@ajax');
Route::resource('/employees', 'EmployeeController');

//Rutas de departamentos
Route::resource('/departments', 'DepartmentController');
Route::resource('/positions', 'PositionController');
Route::resource('/articles', 'ArticleController');
Route::resource('/categories', 'CategoryController');
Route::resource('/brands', 'BrandController');

//Rutas de Activos Fijos
Route::get('/fixed-assets/assign-fixed-asset', 'FixedassetController@showFormAssignFixedAsset')->name('fixed-assets.assign-fixed-asset');
Route::post('/fixed-assets/assign-fixed-asset', 'FixedassetController@assignFixedAsset')->name('fixed-assets.assign-fixed-asset');
Route::get('/fixed-assets/assign-fixed-asset/{fixed_asset}/edit', 'FixedassetController@showFormEditAssignFixedAsset')->name('fixed-assets.edit-assign-fixed-asset');
Route::put('/fixed-assets/assign-fixed-asset/{fixed_asset}', 'FixedassetController@updateAssignFixedAsset')->name('fixed-assets.update-assign-fixed-asset');

Route::resource('/fixed-assets', 'FixedassetController');
Route::resource('/maintenances', 'MaintenanceController');
Route::resource('/storage-cellars', 'StoragecellarController');
Route::post('/delivery-certificates/ajax/edit', 'DeliverycertificateController@ajaxEdit');
Route::post('/delivery-certificates/ajax/delete', 'DeliverycertificateController@ajaxDelete');
Route::resource('/delivery-certificates', 'DeliverycertificateController');
Route::resource('/users', 'UserController');
Route::resource('/roles', 'RoleController');
Route::resource('/status', 'StatusController');

resources/views/modules/deliveries_certificates/create-delivery-certificate.blade.php
@extends('template')
@section('main-content') {{--overview start--}}
<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header"><i class="icon_documents_alt"></i>Delivery Certificate Module</h3>
    <ol class="breadcrumb">
      <li><i class="fa fa-home"></i><a href="{{ route('dashboard') }}">Dashboard</a></li>
      <li><i class="icon_documents_alt"></i><a href="{{ route('delivery-certificates.index') }}">Delivery
          Certificate</a></li>
      <li><i class="fa fa-file-text-o"></i>Create Delivery Certificate</li>
    </ol>
  </div>
</div>
{{--overview end--}} {{--main content start--}}
<div class="row">
  <div class="col-lg-12">
    <section class="panel" id="conten-form">
      <header class="panel-heading">
        <h3>Delivery Certificate Registration Form</h3>
      </header>
      <div class="panel-body">
        <div class="form">
          <form class="form-validate form-horizontal " id="register_form" method="POST"
            action="{{ route('delivery-certificates.store') }}">
            @if (session()->has('status'))
            <div class="alert alert-success center" role="alert">
              {{ session('status') }}
            </div>
            @endif
            <div class="form-group ">
              <label for="code" class="control-label col-lg-2">Code <span class="required">*</span></label>
              <div class="col-lg-3">
                @if ($errors->has('code'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first() }}
                </div>
                @endif
                <input class=" form-control" id="code" name="code" type="text" value="{{ old('code') ?? ($code) }}"
                  readonly required />
              </div>
              <label for="date" class="control-label col-lg-2">Date <span class="required">*</span></label>
              <div class="col-lg-3">
                @if ($errors->has('date'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first() }}
                </div>
                @endif
                <input class=" form-control" id="date" name="date" type="text" value="{{ date('Y-m-d') }}" readonly
                  required />
              </div>
            </div>
            <div class="form-group">
              <label for="department_id" class="control-label col-lg-2">Deparment <span
                  class="required">*</span></label>
              <div class="col-lg-3">
                @if ($errors->has('department_id'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first() }}
                </div>
                @endif
                <select class="form-control" name="department_id" id="department_id" required>
                  <option></option>
                  @foreach ($departments as $department)
                  <option value="{{ $department->id }}">{{ $department->name }}</option>
                  @endforeach
                </select>
              </div>
              <label for="cedula" class="control-label col-lg-2">Cedula <span class="required">*</span></label>
              <div class="col-lg-3">
                @if ($errors->has('cedula'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first() }}
                </div>
                @endif
                <input class=" form-control" id="cedula" name="cedula" type="text" value="{{old('cedula')}}" required />
              </div>
            </div>
            <div class="form-group">
              <label for="employee_id" class="control-label col-lg-2">Received By <span
                  class="required">*</span></label>
              <div class="col-lg-8">
                @if ($errors->has('employee_id'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first() }}
                </div>
                @endif
                <select class="form-control" name="employee_id" id="employee_id" required>
                  <option value=""></option>
                </select>
              </div>
            </div>
            <div class="table-responsive nicescroll-rails top-line" id="ascrail2000">
              <table class="table table-bordered table-advance table-hover">
                <caption class="page-header-table">Articles Descrition</caption>
                <thead class="form-horizontal">
                  <tr>
                    <th class="col-lg-2"><i class="icon_cogs"></i> Fixes Asset</th>
                    <th class="col-lg-2"> Articles</th>
                    <th class="col-lg-1"> Brand</th>
                    <th class="col-lg-1"> Model</th>
                    <th class="col-lg-2">Serial</th>
                    <th class="col-lg-1"> Quantity</th>
                    <th class="col-lg-2"> Price</th>
                    <th class="col-lg-1"> Action</th>
                  </tr>
                </thead>
                <tbody class="form-horizontal" id="tbody">
                  <tr>
                    <td>
                      @if ($errors->has('fixedassets[]'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}
                      </div>
                      @endif
                      <select name="fixedassets[]" id="fixedasset" class="form-control fixedasset" required>
                        <option></option>
                        @foreach ($codefixedassets as $key=>$fixedasset)
                        @switch(strlen($fixedasset->code))
                        @case(1)
                        <option value="{{$fixedasset->id}}">{{"000$fixedasset->code"}}</option>
                        @break
                        @case(2)
                        <option value="{{$fixedasset->id}}">{{"00$fixedasset->code"}}</option>
                        @break
                        @case(3)
                        <option value="{{$fixedasset->id}}">{{"0$fixedasset->code"}}</option>
                        @break
                        @case(4)
                        <option value="{{$fixedasset->id}}">{{$fixedasset->code}}</option>
                        @break
                        @endswitch
                        @endforeach
                      </select>
                    </td>
                    <td>
                      @if ($errors->has('articles[]'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}
                      </div>
                      @endif
                      <input readonly type="text" name="articles[]" id="article" value="" class="form-control" required>
                    </td>
                    <td>
                      @if ($errors->has('brands[]'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}
                      </div>
                      @endif
                      <input readonly type="text" name="brands[]" id="brands" value="" class="form-control" required>
                    </td>
                    <td>
                      @if ($errors->has('models[]'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}
                      </div>
                      @endif
                      <input readonly type="text" name="models[]" id="model" value="" class="form-control" required>
                    </td>
                    <td>
                      @if ($errors->has('serials[]'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}
                      </div>
                      @endif
                      <input readonly type="text" name="serials[]" id="serial" class="form-control" required>
                    </td>
                    <td>
                      @if ($errors->has('quantitys[]'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}
                      </div>
                      @endif
                      <input readonly type="text" name="quantitys[]" id="quantity" class="form-control" required>
                    </td>
                    <td>
                      @if ($errors->has('prices[]'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}
                      </div>
                      @endif
                      <input readonly type="text" name="prices[]" id="price" class="form-control" required>
                    </td>
                    <td>
                      <button class="btn btn-danger" type="button" id="btn-detele"><i
                          class="icon_close_alt2"></i></button>
                    </td>
                  </tr>
                </tbody>
                <tfoot>
                  <tr>
                    <td colspan="6" class="center">Total</td>
                    <td id="priceTotal" class="price">0.00</td>
                  </tr>
                </tfoot>
              </table>
            </div>

            <div class="form-group">
              <div class="col-lg-offset-10 col-lg-2">
                <button class="btn btn-success" type="button" id="addArticle">Add Fixed Asset</button>
              </div>
            </div>
            <div class="form-group ">
              <label for="deliveredBy" class="control-label col-lg-2">Delivered By <span
                  class="required">*</span></label>
              <div class="col-lg-8">
                <span class="form-control">{{Auth::user()->employee->first_name}}
                  {{Auth::user()->employee->first_lastname}}</span>
                @if ($errors->has('deliveredBy[]'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first() }}
                </div>
                @endif
                <input class="form-control" id="deliveredBy" name="deliveredBy" type="hidden"
                  value="{{Auth::user()->id}}" required />
              </div>
            </div>
            <div class="form-group ">
              <label for="observation" class="control-label col-lg-2">Observation </label>
              <div class="col-lg-10">
                @if ($errors->has('observation'))
                <div class="alert alert-danger" role="alert">
                  {{ $errors->first() }}
                </div>
                @endif
                <textarea class="form-control " id="observation" name="observation"></textarea>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="submit">Save</button>
                <button class="btn btn-danger" type="button">Cancel</button>
              </div>
            </div>
            {{ csrf_field() }}
          </form>
        </div>
      </div>
    </section>
  </div>
</div>
{{--main content end--}}
@endsection
@section('js')
<script src="{{asset('js/myscript2.js')}}"></script>
@endsection

resources/views/modules/deliveries_certificates/edit-delivery-certificate-copy-funtional.blade.php
@extends('template.layout')
@section('main-content')
  {{--overview start--}}
  <section class="wrapper">
    <div class="row">
      <div class="col-lg-12">
        <h3 class="page-header"><i class="icon_documents_alt"></i>Delivery Certificate Module</h3>
        <ol class="breadcrumb">
          <li><i class="fa fa-home"></i><a href="{{ route('home') }}">Home</a></li>
          <li><i class="icon_documents_alt"></i><a href="{{ route('delivery-certificates.index') }}">Delivery Certificate</a></li>
          <li><i class="fa fa-file-text-o"></i>Update Delivery Certificate</li>
        </ol>
      </div>
    </div>
  </section>
  {{--overview end--}}
  {{--main content start--}}
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body panel-body-j">
        <section class="panel">
          <header class="panel-heading">
            <h3>Delivery Certificate Update Form</h3>
          </header>
          <div class="panel-body">
            <div class="form">
                <div>
                  <select class="form-control col-lg-3 articles" id="selectFixedasset" style="visibility:hidden">
                    <option></option>
                    @foreach ($fixedAssets as $fixedasset)
                      <option value="{{ $fixedasset->code }}">{{ $fixedasset->code }}</option>
                    @endforeach
                  </select>
                </div>
              <form class="form-validate form-horizontal " id="register_form" method="POST" action="{{ route('delivery-certificates.update', $deliveryC->id) }}">
                @if (session()->has('status'))
                  <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                  </div>
                @endif
                <div class="form-group ">
                  <label for="code" class="control-label col-lg-2">Code</label>
                  <div class="col-lg-3">
                    @if ($errors->has('code'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}  
                      </div>
                    @endif
                  <input class=" form-control" id="code" name="code" type="text" value="{{ $deliveryC->code }}" readonly/>
                  </div>
                  <label for="date" class="control-label col-lg-2">Date</label>
                  <div class="col-lg-3  ">
                    @if ($errors->has('date'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}  
                      </div>
                    @endif
                    <input class=" form-control" id="date" name="date" type="text" value="{{ $deliveryC->date}}" readonly/>
                  </div>
                </div>
                <div class="form-group">
                  <label for="department_id" class="control-label col-lg-2">Deparment</label>
                  <div class="col-lg-3">
                    @if ($errors->has('department_id'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}  
                      </div>
                    @endif
                    <input class=" form-control" id="department_id" name="department_id" type="text" value="{{ $deliveryC->department}}" readonly/>
                  </div>
                  <label for="cedula" class="control-label col-lg-2">Cedula </label>
                  <div class="col-lg-3">
                    @if ($errors->has('cedula'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}  
                      </div>
                    @endif
                    <input class=" form-control" id="cedula" name="cedula" type="text" value="{{$deliveryC->employee->cedula }}" readonly/>
                  </div>
                </div>
                <div class="form-group ">
                  <label for="employee_id" class="control-label col-lg-2">Received By</label>
                  <div class="col-lg-8">
                    @if ($errors->has('employee_id'))
                      <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}  
                      </div>
                    @endif
                    <input class=" form-control" id="employee_id" name="employee_id" type="text" value="{{ $deliveryC->employee->first_name .'  '.  $deliveryC->employee->second_name .'  '. $deliveryC->employee->first_lastname .'  '.  $deliveryC->employee->second_lastname}}" readonly/>
                  </div>
                </div>
                <section class="panel content-table">
                  <header class="panel-heading center"><h3>Articles Descrition</h3></header>
                  <div class="table-responsive nicescroll-rails" id="ascrail2000">
                    <table class="table table-bordered table-advance table-hover">
                      <thead class="form-horizontal">
                        <tr>
                          <th class="col-lg-2"> Fixes Asset</th>
                          <th class="col-lg-2"> Articles</th>
                          <th class="col-lg-1"> Brand</th>
                          <th class="col-lg-1"> Model</th>
                          <th class="col-lg-2"> Serial</th>
                          <th class="col-lg-1"> Quantity</th>
                          <th class="col-lg-2"> Price</th>
                          <th class="col-lg-1"> Action</th>
                        </tr>
                      </thead>
                      <tbody class="form-horizontal" id="tbody">
                        @foreach ($deliveryC->fixedassets as $key => $fixedasset)
                          @foreach ($fixedasset->articles as $key2 => $article)
                            <tr>
                              <td>
                                @if ($errors->has('fixedassets[]'))
                                  <div class="alert alert-danger" role="alert">
                                    {{ $errors->first() }}  
                                  </div>
                                @endif
                                <input class="form-control" type="text" name="fixedassets[]" id="fixedasset{{$key2}}" value="{{ $fixedasset->code}}" readonly>
                              </td>
                              <td>
                                @if ($errors->has('articles[]'))
                                  <div class="alert alert-danger" role="alert">
                                    {{ $errors->first() }}  
                                  </div>
                                @endif
                                <input readonly type="text" name="articles[]" id="article{{$key2}}" value="{{ $article->name }}" class="form-control"
                                  required>
                              </td>
                              <td>
                                @if ($errors->has('brands[]'))
                                  <div class="alert alert-danger" role="alert">
                                    {{ $errors->first() }}  
                                  </div>
                                @endif
                                <input readonly type="text" name="brands[]" id="brands{{$key2}}" value="{{ $article->brand}}" class="form-control" required>
                              </td>
                              <td>
                                @if ($errors->has('models[]'))
                                  <div class="alert alert-danger" role="alert">
                                    {{ $errors->first() }}  
                                  </div>
                                @endif
                                <input readonly type="text" name="models[]" id="model{{$key2}}" value="{{ $article->model}}" class="form-control" required>
                              </td>
                              <td>
                                @if ($errors->has('serials[]'))
                                  <div class="alert alert-danger" role="alert">
                                    {{ $errors->first() }}  
                                  </div>
                                @endif
                                <input readonly type="text" name="serials[]" id="serial{{$key2}}" value="{{ $article->serial}}" class="form-control" required>
                              </td>
                              <td>
                                @if ($errors->has('quantitys[]'))
                                  <div class="alert alert-danger" role="alert">
                                    {{ $errors->first() }}  
                                  </div>
                                @endif
                                <input readonly type="text" name="quantity[]" id="quantity{{$key2}}" value="{{$article->quantity}}" class="form-control" required>
                              </td>
                              <td>
                                @if ($errors->has('prices[]'))
                                  <div class="alert alert-danger" role="alert">
                                    {{ $errors->first() }}  
                                  </div>
                                @endif
                                <input readonly type="text" name="prices[]" id="price{{$key2}}" value="{{$article->price}}" class="form-control" required>
                              </td>
                              <td>
                                <button class="btn btn-danger" type="button" id="btn-detele"><i class="icon_close_alt2"></i></button>
                              </td>
                            </tr>
                            <input type="hidden" value="{{$total += $article->price}}"> 
                          @endforeach
                        @endforeach
                      </tbody>
                      <tfoot>
                        <tr>
                          <td colspan="6" class="center">Total</td>
                          <td class="price"> <input class="form-control" type="text" name="total_edit_delivery" id="total_edit_delivery"  value="{{$total}}" readonly></td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                </section>
                <div class="form-group">
                  <div class="col-lg-offset-10 col-lg-2">
                    <button class="btn btn-success" type="button" id="btnAddFA">Add Fixed Asset</button>
                  </div>
                </div>
                <div class="form-group ">
                  <label for="deliveredBy" class="control-label col-lg-2">Delivered By <span class="required">*</span></label>
                  <div class="col-lg-8">
                    <input class=" form-control" id="deliveredBy" value="{{$deliveryC->user->employee->first_name.'  '.$deliveryC->user->employee->second_name.'  '.$deliveryC->user->employee->first_lastname.'  '.$deliveryC->user->employee->second_lastname}}" name="deliveredBy" type="text" />
                  </div>
                </div>
                <div class="form-group ">
                  <label for="observation" class="control-label col-lg-2">Observation </label>
                  <div class="col-lg-10">
                  <textarea class="form-control " id="observation" name="observation" required>{{$deliveryC->observation}}</textarea> 
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                    <button class="btn btn-primary" type="submit">Save</button>
                    <button class="btn btn-default" type="button">Cancel</button>
                  </div>
                </div>
                {{ csrf_field() }}
                {{ method_field('PUT') }}
              </form>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
  {{--main content end--}}
  @section('js')
  <script src="{{asset('js/myscript4.js')}}"></script>
  @endsection
@endsection

resources/views/modules/deliveries_certificates/list-delivery-certificate.blade.php
@extends('template')
@section('main-content')
{{--overview start--}}
<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header"><i class="icon_documents_alt"></i>Delivery Certificate Module</h3>
    <ol class="breadcrumb">
      <li><i class="fa fa-home"></i><a href="{{ route('dashboard') }}">Dashboard</a></li>
      <li><i class="icon_documents_alt"></i>Articles</li>
    </ol>
  </div>
</div>
{{--overview end--}}
{{--main content start--}}
<div class="row">
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <div class="table-responsive">
            <table class="table table-striped table-advance table-hover">
              <caption class="page-header-table">Delivery Certificates</caption>
              <tbody class="form-horizontal">
                <tr class="form-group">
                  <th class="col-lg-1 col-sm-1 center"> N°</th>
                  <th class="col-lg-1 col-sm-1 center"> <i class="icon_documents_alt"></i> Code</th>
                  <th class="col-lg-2 col-sm-2 center"><i class="fa fa-calendar" aria-hidden="true"></i> Date</th>
                  <th class="col-lg-3 col-sm-2"><i class="fa fa-user" aria-hidden="trues"></i> Employee</th>
                  <th class="col-lg-2 col-sm-2"><i class="fa fa-sitemap" aria-hidden="true"></i> Department</th>
                  <th class="col-lg-3 col-sm-3"><i class="icon_cogs"></i> Action</th>
                </tr>
                @foreach ($deliveriesC as $key => $deliveryC)
                @if (!$deliveryC->deleted_at)
                {{-- {{$key}} --}}
                <tr class="form-group">
                  <td class="col-lg-1 col-sm-1 center">{{ $count}}</td>
                  <td class="col-lg-1 col-sm-1 center">{{ $codes[$key] }}</td>
                  <td class="col-lg-2 col-sm-2 center">{{ $deliveryC->date }}</td>
                  <td class="col-lg-3 col-sm-2"><a
                      href="{{route('employees.show',$deliveryC->employee->id)}}">{{ $deliveryC->employee->first_name . ' '. $deliveryC->employee->first_lastname }}</a>
                  </td>
                  <td class="col-lg-2 col-sm-3 col-sm-3">{{ $deliveryC->employee->department->name }}</td>
                  <td class="col-sm-3">
                    <div class="btn-group btn-group-sm">
                      <a class="btn btn-info" href="{{ route('delivery-certificates.edit', $deliveryC->id) }}"><i
                          class="icon_plus_alt2"></i></a>
                      <a class="btn btn-success " href="{{ route('delivery-certificates.show', $deliveryC->id) }}"><i
                          class="icon_check_alt2"></i></a>
                      <form class="form-delete" method="POST"
                        action="{{ route('delivery-certificates.destroy', $deliveryC->id) }}">
                        <button class="btn btn-sm btn-danger form-delete-button" type="submit"><i
                            class="icon_close_alt2"></i></button>
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                      </form>
                    </div>
                  </td>
                </tr>
                @php $count++ @endphp
                @endif
                @endforeach
              </tbody>
            </table>
            <div class="row">
              <div class="col-lg-offset-5">
                {{$deliveriesC->links() }}
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>
{{--main content end--}}
@endsection